apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: bbox1
  name: bbox1
spec:
  containers:
  - image: busybox
    name: bbox1
    resources: {}
    command:
    - /bin/sh
    - -c
    - sleep 3600;
    env:
      - name: SHOULD_SAY_VALUE1 
        valueFrom: 
          configMapKeyRef:
            key: key1
            name: config-map-demo
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
